WIP another attempt at ast-types flowgen
Better!  Turns out the extra "./" from `find` was confusing things.

$ src=node_modules/ast-types; dest=types/ast-types; \
              time (cd "$src" && find . -name '*.d.ts' ) \
              | while read f; do
    f=${f#./}
    echo "$f"
                  mkdir -p "$dest"/"${f%/*}"
                  node_modules/.bin/flowgen "$src"/"$f" -o "$dest"/"${f%.d.ts}.js.flow" \
                    --add-flow-header
                done
types.d.ts
Parsing types
gen/kinds.d.ts
Parsing kinds
gen/visitor.d.ts
Parsing visitor
gen/builders.d.ts
Parsing builders
gen/namedTypes.d.ts
Parsing namedTypes
SyntaxError: Unexpected token (11:13)
   9 |
  10 | import {
> 11 |             ([obj, keys]) => {
     |             ^
  12 |     return `$Diff<${printers.node.printType(obj)},${Record([keys, {
  13 |       kind: _typescript.default.SyntaxKind.AnyKeyword
  14 |     }], false)}>`;
    at ku (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/parser-babel.js:1:54892)
    at Ou (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/parser-babel.js:1:55033)
    at Object.parse (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/parser-babel.js:1:381521)
    at Object.parse$d [as parse] (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/index.js:12975:19)
    at coreFormat (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/index.js:14525:16)
    at formatWithCursor$1 (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/index.js:14765:14)
    at /home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/index.js:60959:12
    at Object.format (/home/greg/z/mobile/node_modules/flowgen/node_modules/prettier/index.js:60979:12)
    at beautify (/home/greg/z/mobile/node_modules/flowgen/lib/cli/beautifier.js:11:28)
    at outputFile (/home/greg/z/mobile/node_modules/flowgen/lib/cli/runner.js:40:38) {
  loc: { start: { line: 11, column: 13 } },
  codeFrame: '\x1B[0m \x1B[90m  9 |\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 10 |\x1B[39m \x1B[36mimport\x1B[39m {\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 11 |\x1B[39m             ([obj\x1B[33m,\x1B[39m keys]) \x1B[33m=>\x1B[39m {\x1B[0m\n' +
    '\x1B[0m \x1B[90m    |\x1B[39m             \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 12 |\x1B[39m     \x1B[36mreturn\x1B[39m \x1B[32m`$Diff<${printers.node.printType(obj)},${Record([keys, {\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 13 |\x1B[39m \x1B[32m      kind: _typescript.default.SyntaxKind.AnyKeyword\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 14 |\x1B[39m \x1B[32m    }], false)}>`\x1B[39m\x1B[33m;\x1B[39m\x1B[0m'
}
lib/path.d.ts
Parsing path
…
lib/equiv.d.ts
Error -------------------------------------------------------------------------------------------------------- node_modules/ast-types/lib/equiv.d.ts:2:1

  1 | import { Fork } from "../types";
> 2 | export default function (fork: Fork): {
    | ^^^^^^^^^^^^^^ Flow doesn't support unnamed functions
  3 |     (a: any, b: any, problemPath?: any): boolean;
  4 |     assert(a: any, b: any): void;
  5 | };
…
Parsing equiv
lib/scope.d.ts
Parsing scope
…