progress?: base Activity
Now it gets as far as finding the database file (well, its
parent directory) doesn't exist:

```
Cannot open database '/tmp/robolectric-Method_tmp_test14031462555267843593/com.zulipmobile.debug-dataDir/files/SQLite/zulip.db': Directory /tmp/robolectric-Method_tmp_test14031462555267843593/com.zulipmobile.debug-dataDir/files/SQLite doesn't exist
android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/tmp/robolectric-Method_tmp_test14031462555267843593/com.zulipmobile.debug-dataDir/files/SQLite/zulip.db': Directory /tmp/robolectric-Method_tmp_test14031462555267843593/com.zulipmobile.debug-dataDir/files/SQLite doesn't exist
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
…
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:752)
	at com.zulipmobile.ZulipDbOpenHelper.getDatabaseLocked(AppData.kt:166)
…
```